name = "GraphHierarchy"
uuid = "eeea4c8d-ca31-4090-a523-ad0f39bfce72"
authors = ["Giannis Moutsinas"]
version = "0.1.7"

[deps]
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
